// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: language-agent/JVMMetric.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SkyWalking.NetworkProtocol.V3 {

  /// <summary>Holder for reflection information generated from language-agent/JVMMetric.proto</summary>
  public static partial class JVMMetricReflection {

    #region Descriptor
    /// <summary>File descriptor for language-agent/JVMMetric.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static JVMMetricReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5sYW5ndWFnZS1hZ2VudC9KVk1NZXRyaWMucHJvdG8SDXNreXdhbGtpbmcu",
            "djMaE2NvbW1vbi9Db21tb24ucHJvdG8aFGNvbW1vbi9Db21tYW5kLnByb3Rv",
            "ImoKE0pWTU1ldHJpY0NvbGxlY3Rpb24SKQoHbWV0cmljcxgBIAMoCzIYLnNr",
            "eXdhbGtpbmcudjMuSlZNTWV0cmljEg8KB3NlcnZpY2UYAiABKAkSFwoPc2Vy",
            "dmljZUluc3RhbmNlGAMgASgJIvsBCglKVk1NZXRyaWMSDAoEdGltZRgBIAEo",
            "AxIfCgNjcHUYAiABKAsyEi5za3l3YWxraW5nLnYzLkNQVRIlCgZtZW1vcnkY",
            "AyADKAsyFS5za3l3YWxraW5nLnYzLk1lbW9yeRItCgptZW1vcnlQb29sGAQg",
            "AygLMhkuc2t5d2Fsa2luZy52My5NZW1vcnlQb29sEh0KAmdjGAUgAygLMhEu",
            "c2t5d2Fsa2luZy52My5HQxIlCgZ0aHJlYWQYBiABKAsyFS5za3l3YWxraW5n",
            "LnYzLlRocmVhZBIjCgVjbGF6ehgHIAEoCzIULnNreXdhbGtpbmcudjMuQ2xh",
            "c3MiVAoGTWVtb3J5Eg4KBmlzSGVhcBgBIAEoCBIMCgRpbml0GAIgASgDEgsK",
            "A21heBgDIAEoAxIMCgR1c2VkGAQgASgDEhEKCWNvbW1pdHRlZBgFIAEoAyJv",
            "CgpNZW1vcnlQb29sEiUKBHR5cGUYASABKA4yFy5za3l3YWxraW5nLnYzLlBv",
            "b2xUeXBlEgwKBGluaXQYAiABKAMSCwoDbWF4GAMgASgDEgwKBHVzZWQYBCAB",
            "KAMSEQoJY29tbWl0dGVkGAUgASgDIkgKAkdDEiUKBXBoYXNlGAEgASgOMhYu",
            "c2t5d2Fsa2luZy52My5HQ1BoYXNlEg0KBWNvdW50GAIgASgDEgwKBHRpbWUY",
            "AyABKAMizQEKBlRocmVhZBIRCglsaXZlQ291bnQYASABKAMSEwoLZGFlbW9u",
            "Q291bnQYAiABKAMSEQoJcGVha0NvdW50GAMgASgDEiAKGHJ1bm5hYmxlU3Rh",
            "dGVUaHJlYWRDb3VudBgEIAEoAxIfChdibG9ja2VkU3RhdGVUaHJlYWRDb3Vu",
            "dBgFIAEoAxIfChd3YWl0aW5nU3RhdGVUaHJlYWRDb3VudBgGIAEoAxIkChx0",
            "aW1lZFdhaXRpbmdTdGF0ZVRocmVhZENvdW50GAcgASgDImEKBUNsYXNzEhgK",
            "EGxvYWRlZENsYXNzQ291bnQYASABKAMSHwoXdG90YWxVbmxvYWRlZENsYXNz",
            "Q291bnQYAiABKAMSHQoVdG90YWxMb2FkZWRDbGFzc0NvdW50GAMgASgDKqQC",
            "CghQb29sVHlwZRIUChBDT0RFX0NBQ0hFX1VTQUdFEAASEAoMTkVXR0VOX1VT",
            "QUdFEAESEAoMT0xER0VOX1VTQUdFEAISEgoOU1VSVklWT1JfVVNBR0UQAxIR",
            "Cg1QRVJNR0VOX1VTQUdFEAQSEwoPTUVUQVNQQUNFX1VTQUdFEAUSDwoLWkhF",
            "QVBfVVNBR0UQBhIgChxDT01QUkVTU0VEX0NMQVNTX1NQQUNFX1VTQUdFEAcS",
            "HwobQ09ERUhFQVBfTk9OX05NRVRIT0RTX1VTQUdFEAgSJAogQ09ERUhFQVBf",
            "UFJPRklMRURfTk1FVEhPRFNfVVNBR0UQCRIoCiRDT0RFSEVBUF9OT05fUFJP",
            "RklMRURfTk1FVEhPRFNfVVNBR0UQCionCgdHQ1BoYXNlEgcKA05FVxAAEgcK",
            "A09MRBABEgoKBk5PUk1BTBACMmIKFkpWTU1ldHJpY1JlcG9ydFNlcnZpY2US",
            "SAoHY29sbGVjdBIiLnNreXdhbGtpbmcudjMuSlZNTWV0cmljQ29sbGVjdGlv",
            "bhoXLnNreXdhbGtpbmcudjMuQ29tbWFuZHMiAEKTAQozb3JnLmFwYWNoZS5z",
            "a3l3YWxraW5nLmFwbS5uZXR3b3JrLmxhbmd1YWdlLmFnZW50LnYzUAFaOnNr",
            "eXdhbGtpbmcuYXBhY2hlLm9yZy9yZXBvL2dvYXBpL2NvbGxlY3QvbGFuZ3Vh",
            "Z2UvYWdlbnQvdjOqAh1Ta3lXYWxraW5nLk5ldHdvcmtQcm90b2NvbC5WM2IG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SkyWalking.NetworkProtocol.V3.CommonReflection.Descriptor, global::SkyWalking.NetworkProtocol.V3.CommandReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::SkyWalking.NetworkProtocol.V3.PoolType), typeof(global::SkyWalking.NetworkProtocol.V3.GCPhase), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SkyWalking.NetworkProtocol.V3.JVMMetricCollection), global::SkyWalking.NetworkProtocol.V3.JVMMetricCollection.Parser, new[]{ "Metrics", "Service", "ServiceInstance" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SkyWalking.NetworkProtocol.V3.JVMMetric), global::SkyWalking.NetworkProtocol.V3.JVMMetric.Parser, new[]{ "Time", "Cpu", "Memory", "MemoryPool", "Gc", "Thread", "Clazz" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SkyWalking.NetworkProtocol.V3.Memory), global::SkyWalking.NetworkProtocol.V3.Memory.Parser, new[]{ "IsHeap", "Init", "Max", "Used", "Committed" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SkyWalking.NetworkProtocol.V3.MemoryPool), global::SkyWalking.NetworkProtocol.V3.MemoryPool.Parser, new[]{ "Type", "Init", "Max", "Used", "Committed" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SkyWalking.NetworkProtocol.V3.GC), global::SkyWalking.NetworkProtocol.V3.GC.Parser, new[]{ "Phase", "Count", "Time" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SkyWalking.NetworkProtocol.V3.Thread), global::SkyWalking.NetworkProtocol.V3.Thread.Parser, new[]{ "LiveCount", "DaemonCount", "PeakCount", "RunnableStateThreadCount", "BlockedStateThreadCount", "WaitingStateThreadCount", "TimedWaitingStateThreadCount" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SkyWalking.NetworkProtocol.V3.Class), global::SkyWalking.NetworkProtocol.V3.Class.Parser, new[]{ "LoadedClassCount", "TotalUnloadedClassCount", "TotalLoadedClassCount" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum PoolType {
    [pbr::OriginalName("CODE_CACHE_USAGE")] CodeCacheUsage = 0,
    [pbr::OriginalName("NEWGEN_USAGE")] NewgenUsage = 1,
    [pbr::OriginalName("OLDGEN_USAGE")] OldgenUsage = 2,
    [pbr::OriginalName("SURVIVOR_USAGE")] SurvivorUsage = 3,
    [pbr::OriginalName("PERMGEN_USAGE")] PermgenUsage = 4,
    [pbr::OriginalName("METASPACE_USAGE")] MetaspaceUsage = 5,
    [pbr::OriginalName("ZHEAP_USAGE")] ZheapUsage = 6,
    [pbr::OriginalName("COMPRESSED_CLASS_SPACE_USAGE")] CompressedClassSpaceUsage = 7,
    [pbr::OriginalName("CODEHEAP_NON_NMETHODS_USAGE")] CodeheapNonNmethodsUsage = 8,
    [pbr::OriginalName("CODEHEAP_PROFILED_NMETHODS_USAGE")] CodeheapProfiledNmethodsUsage = 9,
    [pbr::OriginalName("CODEHEAP_NON_PROFILED_NMETHODS_USAGE")] CodeheapNonProfiledNmethodsUsage = 10,
  }

  public enum GCPhase {
    [pbr::OriginalName("NEW")] New = 0,
    [pbr::OriginalName("OLD")] Old = 1,
    /// <summary>
    /// The type of GC doesn't have new and old phases, like Z Garbage Collector (ZGC)
    /// </summary>
    [pbr::OriginalName("NORMAL")] Normal = 2,
  }

  #endregion

  #region Messages
  public sealed partial class JVMMetricCollection : pb::IMessage<JVMMetricCollection>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<JVMMetricCollection> _parser = new pb::MessageParser<JVMMetricCollection>(() => new JVMMetricCollection());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<JVMMetricCollection> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SkyWalking.NetworkProtocol.V3.JVMMetricReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public JVMMetricCollection() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public JVMMetricCollection(JVMMetricCollection other) : this() {
      metrics_ = other.metrics_.Clone();
      service_ = other.service_;
      serviceInstance_ = other.serviceInstance_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public JVMMetricCollection Clone() {
      return new JVMMetricCollection(this);
    }

    /// <summary>Field number for the "metrics" field.</summary>
    public const int MetricsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::SkyWalking.NetworkProtocol.V3.JVMMetric> _repeated_metrics_codec
        = pb::FieldCodec.ForMessage(10, global::SkyWalking.NetworkProtocol.V3.JVMMetric.Parser);
    private readonly pbc::RepeatedField<global::SkyWalking.NetworkProtocol.V3.JVMMetric> metrics_ = new pbc::RepeatedField<global::SkyWalking.NetworkProtocol.V3.JVMMetric>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::SkyWalking.NetworkProtocol.V3.JVMMetric> Metrics {
      get { return metrics_; }
    }

    /// <summary>Field number for the "service" field.</summary>
    public const int ServiceFieldNumber = 2;
    private string service_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Service {
      get { return service_; }
      set {
        service_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "serviceInstance" field.</summary>
    public const int ServiceInstanceFieldNumber = 3;
    private string serviceInstance_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ServiceInstance {
      get { return serviceInstance_; }
      set {
        serviceInstance_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as JVMMetricCollection);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(JVMMetricCollection other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!metrics_.Equals(other.metrics_)) return false;
      if (Service != other.Service) return false;
      if (ServiceInstance != other.ServiceInstance) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= metrics_.GetHashCode();
      if (Service.Length != 0) hash ^= Service.GetHashCode();
      if (ServiceInstance.Length != 0) hash ^= ServiceInstance.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      metrics_.WriteTo(output, _repeated_metrics_codec);
      if (Service.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Service);
      }
      if (ServiceInstance.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ServiceInstance);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      metrics_.WriteTo(ref output, _repeated_metrics_codec);
      if (Service.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Service);
      }
      if (ServiceInstance.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ServiceInstance);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += metrics_.CalculateSize(_repeated_metrics_codec);
      if (Service.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Service);
      }
      if (ServiceInstance.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ServiceInstance);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(JVMMetricCollection other) {
      if (other == null) {
        return;
      }
      metrics_.Add(other.metrics_);
      if (other.Service.Length != 0) {
        Service = other.Service;
      }
      if (other.ServiceInstance.Length != 0) {
        ServiceInstance = other.ServiceInstance;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            metrics_.AddEntriesFrom(input, _repeated_metrics_codec);
            break;
          }
          case 18: {
            Service = input.ReadString();
            break;
          }
          case 26: {
            ServiceInstance = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            metrics_.AddEntriesFrom(ref input, _repeated_metrics_codec);
            break;
          }
          case 18: {
            Service = input.ReadString();
            break;
          }
          case 26: {
            ServiceInstance = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class JVMMetric : pb::IMessage<JVMMetric>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<JVMMetric> _parser = new pb::MessageParser<JVMMetric>(() => new JVMMetric());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<JVMMetric> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SkyWalking.NetworkProtocol.V3.JVMMetricReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public JVMMetric() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public JVMMetric(JVMMetric other) : this() {
      time_ = other.time_;
      cpu_ = other.cpu_ != null ? other.cpu_.Clone() : null;
      memory_ = other.memory_.Clone();
      memoryPool_ = other.memoryPool_.Clone();
      gc_ = other.gc_.Clone();
      thread_ = other.thread_ != null ? other.thread_.Clone() : null;
      clazz_ = other.clazz_ != null ? other.clazz_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public JVMMetric Clone() {
      return new JVMMetric(this);
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 1;
    private long time_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    /// <summary>Field number for the "cpu" field.</summary>
    public const int CpuFieldNumber = 2;
    private global::SkyWalking.NetworkProtocol.V3.CPU cpu_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SkyWalking.NetworkProtocol.V3.CPU Cpu {
      get { return cpu_; }
      set {
        cpu_ = value;
      }
    }

    /// <summary>Field number for the "memory" field.</summary>
    public const int MemoryFieldNumber = 3;
    private static readonly pb::FieldCodec<global::SkyWalking.NetworkProtocol.V3.Memory> _repeated_memory_codec
        = pb::FieldCodec.ForMessage(26, global::SkyWalking.NetworkProtocol.V3.Memory.Parser);
    private readonly pbc::RepeatedField<global::SkyWalking.NetworkProtocol.V3.Memory> memory_ = new pbc::RepeatedField<global::SkyWalking.NetworkProtocol.V3.Memory>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::SkyWalking.NetworkProtocol.V3.Memory> Memory {
      get { return memory_; }
    }

    /// <summary>Field number for the "memoryPool" field.</summary>
    public const int MemoryPoolFieldNumber = 4;
    private static readonly pb::FieldCodec<global::SkyWalking.NetworkProtocol.V3.MemoryPool> _repeated_memoryPool_codec
        = pb::FieldCodec.ForMessage(34, global::SkyWalking.NetworkProtocol.V3.MemoryPool.Parser);
    private readonly pbc::RepeatedField<global::SkyWalking.NetworkProtocol.V3.MemoryPool> memoryPool_ = new pbc::RepeatedField<global::SkyWalking.NetworkProtocol.V3.MemoryPool>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::SkyWalking.NetworkProtocol.V3.MemoryPool> MemoryPool {
      get { return memoryPool_; }
    }

    /// <summary>Field number for the "gc" field.</summary>
    public const int GcFieldNumber = 5;
    private static readonly pb::FieldCodec<global::SkyWalking.NetworkProtocol.V3.GC> _repeated_gc_codec
        = pb::FieldCodec.ForMessage(42, global::SkyWalking.NetworkProtocol.V3.GC.Parser);
    private readonly pbc::RepeatedField<global::SkyWalking.NetworkProtocol.V3.GC> gc_ = new pbc::RepeatedField<global::SkyWalking.NetworkProtocol.V3.GC>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::SkyWalking.NetworkProtocol.V3.GC> Gc {
      get { return gc_; }
    }

    /// <summary>Field number for the "thread" field.</summary>
    public const int ThreadFieldNumber = 6;
    private global::SkyWalking.NetworkProtocol.V3.Thread thread_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SkyWalking.NetworkProtocol.V3.Thread Thread {
      get { return thread_; }
      set {
        thread_ = value;
      }
    }

    /// <summary>Field number for the "clazz" field.</summary>
    public const int ClazzFieldNumber = 7;
    private global::SkyWalking.NetworkProtocol.V3.Class clazz_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SkyWalking.NetworkProtocol.V3.Class Clazz {
      get { return clazz_; }
      set {
        clazz_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as JVMMetric);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(JVMMetric other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Time != other.Time) return false;
      if (!object.Equals(Cpu, other.Cpu)) return false;
      if(!memory_.Equals(other.memory_)) return false;
      if(!memoryPool_.Equals(other.memoryPool_)) return false;
      if(!gc_.Equals(other.gc_)) return false;
      if (!object.Equals(Thread, other.Thread)) return false;
      if (!object.Equals(Clazz, other.Clazz)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Time != 0L) hash ^= Time.GetHashCode();
      if (cpu_ != null) hash ^= Cpu.GetHashCode();
      hash ^= memory_.GetHashCode();
      hash ^= memoryPool_.GetHashCode();
      hash ^= gc_.GetHashCode();
      if (thread_ != null) hash ^= Thread.GetHashCode();
      if (clazz_ != null) hash ^= Clazz.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Time != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Time);
      }
      if (cpu_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Cpu);
      }
      memory_.WriteTo(output, _repeated_memory_codec);
      memoryPool_.WriteTo(output, _repeated_memoryPool_codec);
      gc_.WriteTo(output, _repeated_gc_codec);
      if (thread_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Thread);
      }
      if (clazz_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Clazz);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Time != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Time);
      }
      if (cpu_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Cpu);
      }
      memory_.WriteTo(ref output, _repeated_memory_codec);
      memoryPool_.WriteTo(ref output, _repeated_memoryPool_codec);
      gc_.WriteTo(ref output, _repeated_gc_codec);
      if (thread_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Thread);
      }
      if (clazz_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Clazz);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Time != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Time);
      }
      if (cpu_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Cpu);
      }
      size += memory_.CalculateSize(_repeated_memory_codec);
      size += memoryPool_.CalculateSize(_repeated_memoryPool_codec);
      size += gc_.CalculateSize(_repeated_gc_codec);
      if (thread_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Thread);
      }
      if (clazz_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Clazz);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(JVMMetric other) {
      if (other == null) {
        return;
      }
      if (other.Time != 0L) {
        Time = other.Time;
      }
      if (other.cpu_ != null) {
        if (cpu_ == null) {
          Cpu = new global::SkyWalking.NetworkProtocol.V3.CPU();
        }
        Cpu.MergeFrom(other.Cpu);
      }
      memory_.Add(other.memory_);
      memoryPool_.Add(other.memoryPool_);
      gc_.Add(other.gc_);
      if (other.thread_ != null) {
        if (thread_ == null) {
          Thread = new global::SkyWalking.NetworkProtocol.V3.Thread();
        }
        Thread.MergeFrom(other.Thread);
      }
      if (other.clazz_ != null) {
        if (clazz_ == null) {
          Clazz = new global::SkyWalking.NetworkProtocol.V3.Class();
        }
        Clazz.MergeFrom(other.Clazz);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Time = input.ReadInt64();
            break;
          }
          case 18: {
            if (cpu_ == null) {
              Cpu = new global::SkyWalking.NetworkProtocol.V3.CPU();
            }
            input.ReadMessage(Cpu);
            break;
          }
          case 26: {
            memory_.AddEntriesFrom(input, _repeated_memory_codec);
            break;
          }
          case 34: {
            memoryPool_.AddEntriesFrom(input, _repeated_memoryPool_codec);
            break;
          }
          case 42: {
            gc_.AddEntriesFrom(input, _repeated_gc_codec);
            break;
          }
          case 50: {
            if (thread_ == null) {
              Thread = new global::SkyWalking.NetworkProtocol.V3.Thread();
            }
            input.ReadMessage(Thread);
            break;
          }
          case 58: {
            if (clazz_ == null) {
              Clazz = new global::SkyWalking.NetworkProtocol.V3.Class();
            }
            input.ReadMessage(Clazz);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Time = input.ReadInt64();
            break;
          }
          case 18: {
            if (cpu_ == null) {
              Cpu = new global::SkyWalking.NetworkProtocol.V3.CPU();
            }
            input.ReadMessage(Cpu);
            break;
          }
          case 26: {
            memory_.AddEntriesFrom(ref input, _repeated_memory_codec);
            break;
          }
          case 34: {
            memoryPool_.AddEntriesFrom(ref input, _repeated_memoryPool_codec);
            break;
          }
          case 42: {
            gc_.AddEntriesFrom(ref input, _repeated_gc_codec);
            break;
          }
          case 50: {
            if (thread_ == null) {
              Thread = new global::SkyWalking.NetworkProtocol.V3.Thread();
            }
            input.ReadMessage(Thread);
            break;
          }
          case 58: {
            if (clazz_ == null) {
              Clazz = new global::SkyWalking.NetworkProtocol.V3.Class();
            }
            input.ReadMessage(Clazz);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Memory : pb::IMessage<Memory>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Memory> _parser = new pb::MessageParser<Memory>(() => new Memory());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Memory> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SkyWalking.NetworkProtocol.V3.JVMMetricReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Memory() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Memory(Memory other) : this() {
      isHeap_ = other.isHeap_;
      init_ = other.init_;
      max_ = other.max_;
      used_ = other.used_;
      committed_ = other.committed_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Memory Clone() {
      return new Memory(this);
    }

    /// <summary>Field number for the "isHeap" field.</summary>
    public const int IsHeapFieldNumber = 1;
    private bool isHeap_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsHeap {
      get { return isHeap_; }
      set {
        isHeap_ = value;
      }
    }

    /// <summary>Field number for the "init" field.</summary>
    public const int InitFieldNumber = 2;
    private long init_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Init {
      get { return init_; }
      set {
        init_ = value;
      }
    }

    /// <summary>Field number for the "max" field.</summary>
    public const int MaxFieldNumber = 3;
    private long max_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Max {
      get { return max_; }
      set {
        max_ = value;
      }
    }

    /// <summary>Field number for the "used" field.</summary>
    public const int UsedFieldNumber = 4;
    private long used_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Used {
      get { return used_; }
      set {
        used_ = value;
      }
    }

    /// <summary>Field number for the "committed" field.</summary>
    public const int CommittedFieldNumber = 5;
    private long committed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Committed {
      get { return committed_; }
      set {
        committed_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Memory);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Memory other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IsHeap != other.IsHeap) return false;
      if (Init != other.Init) return false;
      if (Max != other.Max) return false;
      if (Used != other.Used) return false;
      if (Committed != other.Committed) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (IsHeap != false) hash ^= IsHeap.GetHashCode();
      if (Init != 0L) hash ^= Init.GetHashCode();
      if (Max != 0L) hash ^= Max.GetHashCode();
      if (Used != 0L) hash ^= Used.GetHashCode();
      if (Committed != 0L) hash ^= Committed.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IsHeap != false) {
        output.WriteRawTag(8);
        output.WriteBool(IsHeap);
      }
      if (Init != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Init);
      }
      if (Max != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Max);
      }
      if (Used != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Used);
      }
      if (Committed != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Committed);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IsHeap != false) {
        output.WriteRawTag(8);
        output.WriteBool(IsHeap);
      }
      if (Init != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Init);
      }
      if (Max != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Max);
      }
      if (Used != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Used);
      }
      if (Committed != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Committed);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (IsHeap != false) {
        size += 1 + 1;
      }
      if (Init != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Init);
      }
      if (Max != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Max);
      }
      if (Used != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Used);
      }
      if (Committed != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Committed);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Memory other) {
      if (other == null) {
        return;
      }
      if (other.IsHeap != false) {
        IsHeap = other.IsHeap;
      }
      if (other.Init != 0L) {
        Init = other.Init;
      }
      if (other.Max != 0L) {
        Max = other.Max;
      }
      if (other.Used != 0L) {
        Used = other.Used;
      }
      if (other.Committed != 0L) {
        Committed = other.Committed;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IsHeap = input.ReadBool();
            break;
          }
          case 16: {
            Init = input.ReadInt64();
            break;
          }
          case 24: {
            Max = input.ReadInt64();
            break;
          }
          case 32: {
            Used = input.ReadInt64();
            break;
          }
          case 40: {
            Committed = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            IsHeap = input.ReadBool();
            break;
          }
          case 16: {
            Init = input.ReadInt64();
            break;
          }
          case 24: {
            Max = input.ReadInt64();
            break;
          }
          case 32: {
            Used = input.ReadInt64();
            break;
          }
          case 40: {
            Committed = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class MemoryPool : pb::IMessage<MemoryPool>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MemoryPool> _parser = new pb::MessageParser<MemoryPool>(() => new MemoryPool());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MemoryPool> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SkyWalking.NetworkProtocol.V3.JVMMetricReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MemoryPool() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MemoryPool(MemoryPool other) : this() {
      type_ = other.type_;
      init_ = other.init_;
      max_ = other.max_;
      used_ = other.used_;
      committed_ = other.committed_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MemoryPool Clone() {
      return new MemoryPool(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::SkyWalking.NetworkProtocol.V3.PoolType type_ = global::SkyWalking.NetworkProtocol.V3.PoolType.CodeCacheUsage;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SkyWalking.NetworkProtocol.V3.PoolType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "init" field.</summary>
    public const int InitFieldNumber = 2;
    private long init_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Init {
      get { return init_; }
      set {
        init_ = value;
      }
    }

    /// <summary>Field number for the "max" field.</summary>
    public const int MaxFieldNumber = 3;
    private long max_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Max {
      get { return max_; }
      set {
        max_ = value;
      }
    }

    /// <summary>Field number for the "used" field.</summary>
    public const int UsedFieldNumber = 4;
    private long used_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Used {
      get { return used_; }
      set {
        used_ = value;
      }
    }

    /// <summary>Field number for the "committed" field.</summary>
    public const int CommittedFieldNumber = 5;
    private long committed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Committed {
      get { return committed_; }
      set {
        committed_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MemoryPool);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MemoryPool other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Init != other.Init) return false;
      if (Max != other.Max) return false;
      if (Used != other.Used) return false;
      if (Committed != other.Committed) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::SkyWalking.NetworkProtocol.V3.PoolType.CodeCacheUsage) hash ^= Type.GetHashCode();
      if (Init != 0L) hash ^= Init.GetHashCode();
      if (Max != 0L) hash ^= Max.GetHashCode();
      if (Used != 0L) hash ^= Used.GetHashCode();
      if (Committed != 0L) hash ^= Committed.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::SkyWalking.NetworkProtocol.V3.PoolType.CodeCacheUsage) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Init != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Init);
      }
      if (Max != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Max);
      }
      if (Used != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Used);
      }
      if (Committed != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Committed);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::SkyWalking.NetworkProtocol.V3.PoolType.CodeCacheUsage) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Init != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Init);
      }
      if (Max != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Max);
      }
      if (Used != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Used);
      }
      if (Committed != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Committed);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::SkyWalking.NetworkProtocol.V3.PoolType.CodeCacheUsage) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Init != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Init);
      }
      if (Max != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Max);
      }
      if (Used != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Used);
      }
      if (Committed != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Committed);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MemoryPool other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::SkyWalking.NetworkProtocol.V3.PoolType.CodeCacheUsage) {
        Type = other.Type;
      }
      if (other.Init != 0L) {
        Init = other.Init;
      }
      if (other.Max != 0L) {
        Max = other.Max;
      }
      if (other.Used != 0L) {
        Used = other.Used;
      }
      if (other.Committed != 0L) {
        Committed = other.Committed;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::SkyWalking.NetworkProtocol.V3.PoolType) input.ReadEnum();
            break;
          }
          case 16: {
            Init = input.ReadInt64();
            break;
          }
          case 24: {
            Max = input.ReadInt64();
            break;
          }
          case 32: {
            Used = input.ReadInt64();
            break;
          }
          case 40: {
            Committed = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::SkyWalking.NetworkProtocol.V3.PoolType) input.ReadEnum();
            break;
          }
          case 16: {
            Init = input.ReadInt64();
            break;
          }
          case 24: {
            Max = input.ReadInt64();
            break;
          }
          case 32: {
            Used = input.ReadInt64();
            break;
          }
          case 40: {
            Committed = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class GC : pb::IMessage<GC>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GC> _parser = new pb::MessageParser<GC>(() => new GC());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GC> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SkyWalking.NetworkProtocol.V3.JVMMetricReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GC() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GC(GC other) : this() {
      phase_ = other.phase_;
      count_ = other.count_;
      time_ = other.time_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GC Clone() {
      return new GC(this);
    }

    /// <summary>Field number for the "phase" field.</summary>
    public const int PhaseFieldNumber = 1;
    private global::SkyWalking.NetworkProtocol.V3.GCPhase phase_ = global::SkyWalking.NetworkProtocol.V3.GCPhase.New;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SkyWalking.NetworkProtocol.V3.GCPhase Phase {
      get { return phase_; }
      set {
        phase_ = value;
      }
    }

    /// <summary>Field number for the "count" field.</summary>
    public const int CountFieldNumber = 2;
    private long count_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Count {
      get { return count_; }
      set {
        count_ = value;
      }
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 3;
    private long time_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GC);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GC other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Phase != other.Phase) return false;
      if (Count != other.Count) return false;
      if (Time != other.Time) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Phase != global::SkyWalking.NetworkProtocol.V3.GCPhase.New) hash ^= Phase.GetHashCode();
      if (Count != 0L) hash ^= Count.GetHashCode();
      if (Time != 0L) hash ^= Time.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Phase != global::SkyWalking.NetworkProtocol.V3.GCPhase.New) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Phase);
      }
      if (Count != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Count);
      }
      if (Time != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Time);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Phase != global::SkyWalking.NetworkProtocol.V3.GCPhase.New) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Phase);
      }
      if (Count != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Count);
      }
      if (Time != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Time);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Phase != global::SkyWalking.NetworkProtocol.V3.GCPhase.New) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Phase);
      }
      if (Count != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Count);
      }
      if (Time != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Time);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GC other) {
      if (other == null) {
        return;
      }
      if (other.Phase != global::SkyWalking.NetworkProtocol.V3.GCPhase.New) {
        Phase = other.Phase;
      }
      if (other.Count != 0L) {
        Count = other.Count;
      }
      if (other.Time != 0L) {
        Time = other.Time;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Phase = (global::SkyWalking.NetworkProtocol.V3.GCPhase) input.ReadEnum();
            break;
          }
          case 16: {
            Count = input.ReadInt64();
            break;
          }
          case 24: {
            Time = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Phase = (global::SkyWalking.NetworkProtocol.V3.GCPhase) input.ReadEnum();
            break;
          }
          case 16: {
            Count = input.ReadInt64();
            break;
          }
          case 24: {
            Time = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// See: https://docs.oracle.com/javase/8/docs/api/java/lang/management/ThreadMXBean.html
  /// </summary>
  public sealed partial class Thread : pb::IMessage<Thread>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Thread> _parser = new pb::MessageParser<Thread>(() => new Thread());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Thread> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SkyWalking.NetworkProtocol.V3.JVMMetricReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Thread() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Thread(Thread other) : this() {
      liveCount_ = other.liveCount_;
      daemonCount_ = other.daemonCount_;
      peakCount_ = other.peakCount_;
      runnableStateThreadCount_ = other.runnableStateThreadCount_;
      blockedStateThreadCount_ = other.blockedStateThreadCount_;
      waitingStateThreadCount_ = other.waitingStateThreadCount_;
      timedWaitingStateThreadCount_ = other.timedWaitingStateThreadCount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Thread Clone() {
      return new Thread(this);
    }

    /// <summary>Field number for the "liveCount" field.</summary>
    public const int LiveCountFieldNumber = 1;
    private long liveCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long LiveCount {
      get { return liveCount_; }
      set {
        liveCount_ = value;
      }
    }

    /// <summary>Field number for the "daemonCount" field.</summary>
    public const int DaemonCountFieldNumber = 2;
    private long daemonCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long DaemonCount {
      get { return daemonCount_; }
      set {
        daemonCount_ = value;
      }
    }

    /// <summary>Field number for the "peakCount" field.</summary>
    public const int PeakCountFieldNumber = 3;
    private long peakCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long PeakCount {
      get { return peakCount_; }
      set {
        peakCount_ = value;
      }
    }

    /// <summary>Field number for the "runnableStateThreadCount" field.</summary>
    public const int RunnableStateThreadCountFieldNumber = 4;
    private long runnableStateThreadCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long RunnableStateThreadCount {
      get { return runnableStateThreadCount_; }
      set {
        runnableStateThreadCount_ = value;
      }
    }

    /// <summary>Field number for the "blockedStateThreadCount" field.</summary>
    public const int BlockedStateThreadCountFieldNumber = 5;
    private long blockedStateThreadCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long BlockedStateThreadCount {
      get { return blockedStateThreadCount_; }
      set {
        blockedStateThreadCount_ = value;
      }
    }

    /// <summary>Field number for the "waitingStateThreadCount" field.</summary>
    public const int WaitingStateThreadCountFieldNumber = 6;
    private long waitingStateThreadCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long WaitingStateThreadCount {
      get { return waitingStateThreadCount_; }
      set {
        waitingStateThreadCount_ = value;
      }
    }

    /// <summary>Field number for the "timedWaitingStateThreadCount" field.</summary>
    public const int TimedWaitingStateThreadCountFieldNumber = 7;
    private long timedWaitingStateThreadCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long TimedWaitingStateThreadCount {
      get { return timedWaitingStateThreadCount_; }
      set {
        timedWaitingStateThreadCount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Thread);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Thread other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LiveCount != other.LiveCount) return false;
      if (DaemonCount != other.DaemonCount) return false;
      if (PeakCount != other.PeakCount) return false;
      if (RunnableStateThreadCount != other.RunnableStateThreadCount) return false;
      if (BlockedStateThreadCount != other.BlockedStateThreadCount) return false;
      if (WaitingStateThreadCount != other.WaitingStateThreadCount) return false;
      if (TimedWaitingStateThreadCount != other.TimedWaitingStateThreadCount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LiveCount != 0L) hash ^= LiveCount.GetHashCode();
      if (DaemonCount != 0L) hash ^= DaemonCount.GetHashCode();
      if (PeakCount != 0L) hash ^= PeakCount.GetHashCode();
      if (RunnableStateThreadCount != 0L) hash ^= RunnableStateThreadCount.GetHashCode();
      if (BlockedStateThreadCount != 0L) hash ^= BlockedStateThreadCount.GetHashCode();
      if (WaitingStateThreadCount != 0L) hash ^= WaitingStateThreadCount.GetHashCode();
      if (TimedWaitingStateThreadCount != 0L) hash ^= TimedWaitingStateThreadCount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (LiveCount != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(LiveCount);
      }
      if (DaemonCount != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(DaemonCount);
      }
      if (PeakCount != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(PeakCount);
      }
      if (RunnableStateThreadCount != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(RunnableStateThreadCount);
      }
      if (BlockedStateThreadCount != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(BlockedStateThreadCount);
      }
      if (WaitingStateThreadCount != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(WaitingStateThreadCount);
      }
      if (TimedWaitingStateThreadCount != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(TimedWaitingStateThreadCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (LiveCount != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(LiveCount);
      }
      if (DaemonCount != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(DaemonCount);
      }
      if (PeakCount != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(PeakCount);
      }
      if (RunnableStateThreadCount != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(RunnableStateThreadCount);
      }
      if (BlockedStateThreadCount != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(BlockedStateThreadCount);
      }
      if (WaitingStateThreadCount != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(WaitingStateThreadCount);
      }
      if (TimedWaitingStateThreadCount != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(TimedWaitingStateThreadCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LiveCount != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(LiveCount);
      }
      if (DaemonCount != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(DaemonCount);
      }
      if (PeakCount != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PeakCount);
      }
      if (RunnableStateThreadCount != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(RunnableStateThreadCount);
      }
      if (BlockedStateThreadCount != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(BlockedStateThreadCount);
      }
      if (WaitingStateThreadCount != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(WaitingStateThreadCount);
      }
      if (TimedWaitingStateThreadCount != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TimedWaitingStateThreadCount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Thread other) {
      if (other == null) {
        return;
      }
      if (other.LiveCount != 0L) {
        LiveCount = other.LiveCount;
      }
      if (other.DaemonCount != 0L) {
        DaemonCount = other.DaemonCount;
      }
      if (other.PeakCount != 0L) {
        PeakCount = other.PeakCount;
      }
      if (other.RunnableStateThreadCount != 0L) {
        RunnableStateThreadCount = other.RunnableStateThreadCount;
      }
      if (other.BlockedStateThreadCount != 0L) {
        BlockedStateThreadCount = other.BlockedStateThreadCount;
      }
      if (other.WaitingStateThreadCount != 0L) {
        WaitingStateThreadCount = other.WaitingStateThreadCount;
      }
      if (other.TimedWaitingStateThreadCount != 0L) {
        TimedWaitingStateThreadCount = other.TimedWaitingStateThreadCount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            LiveCount = input.ReadInt64();
            break;
          }
          case 16: {
            DaemonCount = input.ReadInt64();
            break;
          }
          case 24: {
            PeakCount = input.ReadInt64();
            break;
          }
          case 32: {
            RunnableStateThreadCount = input.ReadInt64();
            break;
          }
          case 40: {
            BlockedStateThreadCount = input.ReadInt64();
            break;
          }
          case 48: {
            WaitingStateThreadCount = input.ReadInt64();
            break;
          }
          case 56: {
            TimedWaitingStateThreadCount = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            LiveCount = input.ReadInt64();
            break;
          }
          case 16: {
            DaemonCount = input.ReadInt64();
            break;
          }
          case 24: {
            PeakCount = input.ReadInt64();
            break;
          }
          case 32: {
            RunnableStateThreadCount = input.ReadInt64();
            break;
          }
          case 40: {
            BlockedStateThreadCount = input.ReadInt64();
            break;
          }
          case 48: {
            WaitingStateThreadCount = input.ReadInt64();
            break;
          }
          case 56: {
            TimedWaitingStateThreadCount = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// See: https://docs.oracle.com/javase/8/docs/api/java/lang/management/ClassLoadingMXBean.html
  /// </summary>
  public sealed partial class Class : pb::IMessage<Class>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Class> _parser = new pb::MessageParser<Class>(() => new Class());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Class> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SkyWalking.NetworkProtocol.V3.JVMMetricReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Class() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Class(Class other) : this() {
      loadedClassCount_ = other.loadedClassCount_;
      totalUnloadedClassCount_ = other.totalUnloadedClassCount_;
      totalLoadedClassCount_ = other.totalLoadedClassCount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Class Clone() {
      return new Class(this);
    }

    /// <summary>Field number for the "loadedClassCount" field.</summary>
    public const int LoadedClassCountFieldNumber = 1;
    private long loadedClassCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long LoadedClassCount {
      get { return loadedClassCount_; }
      set {
        loadedClassCount_ = value;
      }
    }

    /// <summary>Field number for the "totalUnloadedClassCount" field.</summary>
    public const int TotalUnloadedClassCountFieldNumber = 2;
    private long totalUnloadedClassCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long TotalUnloadedClassCount {
      get { return totalUnloadedClassCount_; }
      set {
        totalUnloadedClassCount_ = value;
      }
    }

    /// <summary>Field number for the "totalLoadedClassCount" field.</summary>
    public const int TotalLoadedClassCountFieldNumber = 3;
    private long totalLoadedClassCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long TotalLoadedClassCount {
      get { return totalLoadedClassCount_; }
      set {
        totalLoadedClassCount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Class);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Class other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LoadedClassCount != other.LoadedClassCount) return false;
      if (TotalUnloadedClassCount != other.TotalUnloadedClassCount) return false;
      if (TotalLoadedClassCount != other.TotalLoadedClassCount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LoadedClassCount != 0L) hash ^= LoadedClassCount.GetHashCode();
      if (TotalUnloadedClassCount != 0L) hash ^= TotalUnloadedClassCount.GetHashCode();
      if (TotalLoadedClassCount != 0L) hash ^= TotalLoadedClassCount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (LoadedClassCount != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(LoadedClassCount);
      }
      if (TotalUnloadedClassCount != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(TotalUnloadedClassCount);
      }
      if (TotalLoadedClassCount != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TotalLoadedClassCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (LoadedClassCount != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(LoadedClassCount);
      }
      if (TotalUnloadedClassCount != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(TotalUnloadedClassCount);
      }
      if (TotalLoadedClassCount != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TotalLoadedClassCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LoadedClassCount != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(LoadedClassCount);
      }
      if (TotalUnloadedClassCount != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TotalUnloadedClassCount);
      }
      if (TotalLoadedClassCount != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TotalLoadedClassCount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Class other) {
      if (other == null) {
        return;
      }
      if (other.LoadedClassCount != 0L) {
        LoadedClassCount = other.LoadedClassCount;
      }
      if (other.TotalUnloadedClassCount != 0L) {
        TotalUnloadedClassCount = other.TotalUnloadedClassCount;
      }
      if (other.TotalLoadedClassCount != 0L) {
        TotalLoadedClassCount = other.TotalLoadedClassCount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            LoadedClassCount = input.ReadInt64();
            break;
          }
          case 16: {
            TotalUnloadedClassCount = input.ReadInt64();
            break;
          }
          case 24: {
            TotalLoadedClassCount = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            LoadedClassCount = input.ReadInt64();
            break;
          }
          case 16: {
            TotalUnloadedClassCount = input.ReadInt64();
            break;
          }
          case 24: {
            TotalLoadedClassCount = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
