// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: language-agent/JVMMetricCompat.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SkyWalking.NetworkProtocol.V3.Compat {

  /// <summary>Holder for reflection information generated from language-agent/JVMMetricCompat.proto</summary>
  public static partial class JVMMetricCompatReflection {

    #region Descriptor
    /// <summary>File descriptor for language-agent/JVMMetricCompat.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static JVMMetricCompatReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRsYW5ndWFnZS1hZ2VudC9KVk1NZXRyaWNDb21wYXQucHJvdG8aFGNvbW1v",
            "bi9Db21tYW5kLnByb3RvGh5sYW5ndWFnZS1hZ2VudC9KVk1NZXRyaWMucHJv",
            "dG8yYgoWSlZNTWV0cmljUmVwb3J0U2VydmljZRJICgdjb2xsZWN0EiIuc2t5",
            "d2Fsa2luZy52My5KVk1NZXRyaWNDb2xsZWN0aW9uGhcuc2t5d2Fsa2luZy52",
            "My5Db21tYW5kcyIAQqsBCjpvcmcuYXBhY2hlLnNreXdhbGtpbmcuYXBtLm5l",
            "dHdvcmsubGFuZ3VhZ2UuYWdlbnQudjMuY29tcGF0UAFaQXNreXdhbGtpbmcu",
            "YXBhY2hlLm9yZy9yZXBvL2dvYXBpL2NvbGxlY3QvbGFuZ3VhZ2UvYWdlbnQv",
            "djMvY29tcGF0uAEBqgIkU2t5V2Fsa2luZy5OZXR3b3JrUHJvdG9jb2wuVjMu",
            "Q29tcGF0YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SkyWalking.NetworkProtocol.V3.CommandReflection.Descriptor, global::SkyWalking.NetworkProtocol.V3.JVMMetricReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
