// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: language-agent/MeterCompat.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SkyWalking.NetworkProtocol.V3.Compat {

  /// <summary>Holder for reflection information generated from language-agent/MeterCompat.proto</summary>
  public static partial class MeterCompatReflection {

    #region Descriptor
    /// <summary>File descriptor for language-agent/MeterCompat.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MeterCompatReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBsYW5ndWFnZS1hZ2VudC9NZXRlckNvbXBhdC5wcm90bxoUY29tbW9uL0Nv",
            "bW1hbmQucHJvdG8aGmxhbmd1YWdlLWFnZW50L01ldGVyLnByb3RvMlYKEk1l",
            "dGVyUmVwb3J0U2VydmljZRJACgdjb2xsZWN0Ehguc2t5d2Fsa2luZy52My5N",
            "ZXRlckRhdGEaFy5za3l3YWxraW5nLnYzLkNvbW1hbmRzIgAoAUKrAQo6b3Jn",
            "LmFwYWNoZS5za3l3YWxraW5nLmFwbS5uZXR3b3JrLmxhbmd1YWdlLmFnZW50",
            "LnYzLmNvbXBhdFABWkFza3l3YWxraW5nLmFwYWNoZS5vcmcvcmVwby9nb2Fw",
            "aS9jb2xsZWN0L2xhbmd1YWdlL2FnZW50L3YzL2NvbXBhdLgBAaoCJFNreVdh",
            "bGtpbmcuTmV0d29ya1Byb3RvY29sLlYzLkNvbXBhdGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SkyWalking.NetworkProtocol.V3.CommandReflection.Descriptor, global::Skywalking.V3.MeterReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
