// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: profile/ProfileCompat.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SkyWalking.NetworkProtocol.V3.Compat {

  /// <summary>Holder for reflection information generated from profile/ProfileCompat.proto</summary>
  public static partial class ProfileCompatReflection {

    #region Descriptor
    /// <summary>File descriptor for profile/ProfileCompat.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProfileCompatReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chtwcm9maWxlL1Byb2ZpbGVDb21wYXQucHJvdG8aFGNvbW1vbi9Db21tYW5k",
            "LnByb3RvGhVwcm9maWxlL1Byb2ZpbGUucHJvdG8ykAIKC1Byb2ZpbGVUYXNr",
            "ElsKFmdldFByb2ZpbGVUYXNrQ29tbWFuZHMSJi5za3l3YWxraW5nLnYzLlBy",
            "b2ZpbGVUYXNrQ29tbWFuZFF1ZXJ5Ghcuc2t5d2Fsa2luZy52My5Db21tYW5k",
            "cyIAEk0KD2NvbGxlY3RTbmFwc2hvdBIdLnNreXdhbGtpbmcudjMuVGhyZWFk",
            "U25hcHNob3QaFy5za3l3YWxraW5nLnYzLkNvbW1hbmRzIgAoARJVChByZXBv",
            "cnRUYXNrRmluaXNoEiYuc2t5d2Fsa2luZy52My5Qcm9maWxlVGFza0Zpbmlz",
            "aFJlcG9ydBoXLnNreXdhbGtpbmcudjMuQ29tbWFuZHMiAEKvAQo8b3JnLmFw",
            "YWNoZS5za3l3YWxraW5nLmFwbS5uZXR3b3JrLmxhbmd1YWdlLnByb2ZpbGUu",
            "djMuY29tcGF0UAFaQ3NreXdhbGtpbmcuYXBhY2hlLm9yZy9yZXBvL2dvYXBp",
            "L2NvbGxlY3QvbGFuZ3VhZ2UvcHJvZmlsZS92My9jb21wYXS4AQGqAiRTa3lX",
            "YWxraW5nLk5ldHdvcmtQcm90b2NvbC5WMy5Db21wYXRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SkyWalking.NetworkProtocol.V3.CommandReflection.Descriptor, global::SkyWalking.NetworkProtocol.V3.ProfileReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
